apiVersion: 0.1.0
environments:
  default:
    destination:
      namespace: interspire-production
      server: https://35.184.68.121
    k8sVersion: v1.7.0
    path: default
kind: ksonnet.io/app
name: ksonnet-example-3
registries:
  incubator:
    gitVersion:
      commitSha: 40285d8a14f1ac5787e405e1023cf0c07f6aa28c
      refSpec: master
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
version: 0.0.1
